---
title: "Analise_Variancia"
author: "massainesousa"
date: "2022-06-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Analise de variancia Individual

```{r}
library("lme4"); library(tidyverse)
library("EnvStats")
library("ggridges")
library(viridis)
library(gridExtra)
library(sommer)
library(gt)
library(dplyr)


dados <- read.table(here::here("data", "Planilha epocas Junho22.txt"), header=T, sep="\t", na.strings="NA")
dados <- dados[!is.na(dados$Ano),]
dados$Obs <- factor(dados$Obs)
dados <- dados[dados$Obs=="Ok",]
dados$Ano <- factor(dados$Ano)
dados$Mes <- factor(dados$Mes)
dados$Epoca <- factor(dados$Epoca)
dados$Acession_name <- factor(dados$Acession_name)
dados$bloco <- factor(dados$bloco)
dados$bloco <- factor(paste(dados$bloco,dados$Epoca,sep = ""))
dados$Ramificacao <- factor(dados$Ramificacao)
dadost0 <- subset(dados,dados$Ramificacao=="Ram0")
dadost0$CompR <- as.numeric(dadost0$CompR)

dados1 <- read.table(here::here("data", "DadosEpocas_NotaFloresV2.txt"), header=T, sep="\t", na.strings="NA", strip.white=TRUE, check.names=FALSE)
dados1$bloco <- as.factor(dados1$bloco)
dados1$Acession_name <- as.factor(dados1$Acession_name)
dados1$Epoca <- as.factor(dados1$Epoca)
dados1$NP <- sqrt(dados1$NP)
dados1$NM <- sqrt(dados1$NM)
dados1 <- dados1[!dados1$Acession_name=="BGM-0945",]
dados1 <- dados1[!dados1$Acession_name=="BRS-PotiBranca",]
dados1 <- dados1[,c(4,30:31)]

dados2 <- merge(dadost0, dados1, by = "plot_name", all.x=T)
head(dados2)
```

# Analise de variancia individual
```{r}
dados3 <- dados2[,c("Acession_name","bloco","plant_number","Epoca",
                    "DAPR1ano","DAPR1ano_Ext", "NumEvRam","Altura.total","CompR",
                    "NM","NP","NumTFruto", "NumTSem")]

dados3$NumTFruto <- sqrt(dados3$NumTFruto)
dados3$NumTSem <- sqrt(dados3$NumTSem)

```


```{r}
model <- list()
traits <- c("DAPR1ano_Ext", "NumEvRam","CompR","NM","NP","NumTFruto")
blupsL <- list()
model <- list()
analise <- list()
parametros <- matrix(NA,ncol=7,nrow=length(traits))
parametrosL <- list()

for (j in 1:4) {

  model[[j]] <- mmer(fixed =  cbind(DAPR1ano_Ext, NumEvRam,CompR,NM,NP,NumTFruto)
                     ~ bloco,
              random = ~ Acession_name, getPEV = T, data =     subset(dados3,dados3$Epoca==j) %>%                     
              droplevels(.$bloco))
  
  blups <- do.call(cbind,model[[j]]$U$Acession_name)
  Var_Cor <- as.data.frame(do.call(rbind,model[[j]]$sigma)) 

  for (i in 1:length(traits)) {  
   vblup <- mean(diag(model[[1]]$PevU$Acession_name[[i]]))
   parametros[i,2] <- rownames(Var_Cor)[i]
   parametros[i,3] <- round(Var_Cor[i,i]/(Var_Cor[i,i] + (Var_Cor[length(traits)+i,i]/3)),2)
   parametros[i,4] <- 1 - (vblup / (2 * Var_Cor[i,i])) ## cullis
   parametros[i,5] <- round(subset(model[[j]]$Beta,model[[j]]$Beta$Effect=="(Intercept)")[i,3],2)
   parametros[i,6] <- round(Var_Cor[i,i],2)
   parametros[i,7] <- round(Var_Cor[length(traits)+i,i],2)
   blups[,i] <- blups[,i]+subset(model[[j]]$Beta,model[[j]]$Beta$Effect=="(Intercept)")[i,3]
  }
  blupsL[[j]] <- blups 
  parametros[,1] <- j
  parametrosL[[j]] <- as.data.frame(parametros)
   
}  

Var_Cor$Componemte <- rep(c("Genetica","Residual"),each=6)
Res.parametros <- do.call(rbind,parametrosL)
colnames(Res.parametros) <- c("Epoca","Trait","Herdabilidade","H.Cullis","Media","Variancia","Residuo")
Res.parametros$H.Cullis <- round(as.numeric(Res.parametros$H.Cullis),digits=2)
Res.parametros%>% gt::gt()
Var_Cor %>% gt::gt()

#save(Var_Cor,Res.parametros,model, file=here::here("output","resultados.RData"))
#save(blupsL,dados3,file=here::here("output","blups_EP.RData"))
#save.image(file=here::here("output","Modelo.RData"))
## h2.cullis= 1 - (PEV.u/2*Vg)

```

## Covariancia genética entre traits por época (analise multitrait)
```{r}
load(file=here::here("output","resultados.RData"))
Var_cov_ep <- list()

for (j in 1:4) {
  Var_cov_ep[[j]] <- as.data.frame(do.call(rbind,model[[j]]$sigma))
  Var_cov_ep[[j]]$epoca <- j
}

Var_cov_total <- as.data.frame(do.call(rbind,Var_cov_ep))
Var_cov_total[,1:6] <- round(Var_cov_total[,1:6],2)
Var_cov_total$trait <- rownames(Var_cov_total)
Var_cov_total %>% gt::gt() 

```




## Analise de variancia conjunta
```{r}

 modelconj <- mmer(fixed =  cbind(DAPR1ano_Ext, NumEvRam,CompR,NM,NP,NumTFruto)
                     ~ bloco + Epoca,
              random = ~ Acession_name + Acession_name:Epoca, getPEV = T, data = dados3)

#save(modelconj,file=here::here("output","modelconj.RData"))
load(file=here::here("output","modelconj.RData"))

blupsConj <- do.call(cbind,modelconj$U$Acession_name)
```

## terceira tentativa model com interacao
```{r}

modelconj2 <- mmer(cbind(DAPR1ano_Ext, NumEvRam,CompR,NM,NP,NumTFruto)~1,
                random= ~ Acession_name + Epoca + Acession_name:Epoca + Epoca:bloco,
                rcov= ~ units, nIters=3,
                data=dados3, verbose = FALSE)

```


### Carregar RData
```{r}
load(file=here::here("output","modelconj2.RData"))
n.env <- 4

traits <- c("DAPR1ano_Ext", "NumEvRam","CompR","NM","NP","NumTFruto")
parametros <- matrix(NA,ncol=6,nrow=length(traits))
colnames(parametros) <- c("Herdabilidade","Media","Var_G","Var_E","Var_GxE","Residuo")

## herdabilidade
parametros[1,1] <- as.numeric((vpredict(modelconj2, h2 ~ V1 / ( V1 + (V43/n.env) + (V85/(2*n.env)))))[1])
parametros[2,1] <- as.numeric((vpredict(modelconj2, h2 ~ V7 / ( V7 + (V49/n.env) + (V91/(2*n.env)))))[1])
parametros[3,1] <- as.numeric((vpredict(modelconj2, h2 ~ V12 /(V12 + (V54/n.env) + (V96/(2*n.env)))))[1])
parametros[4,1] <- as.numeric((vpredict(modelconj2, h2 ~ V16 /(V16 + (V58/n.env) + (V100/(2*n.env)))))[1])
parametros[5,1] <- as.numeric((vpredict(modelconj2, h2 ~ V19 / (V19 + (V61/n.env) +(V103/(2*n.env)))))[1])
parametros[6,1] <- as.numeric((vpredict(modelconj2, h2 ~ V21 / (V21 + (V63/n.env) + (V105/(2*n.env)))))[1])

## demais componentes
comp <- as.data.frame(summary(modelconj2)$varcomp)
comp <- subset(comp,comp$Constraint=="Positive")
comp$seq <- seq(1:30)

parametros[,2] <- round(modelconj2$Beta$Estimate,2)
parametros[,3] <- round(comp$VarComp[1:6],2)
parametros[,4] <- round(comp$VarComp[7:12],2)
parametros[,5] <- round(comp$VarComp[13:18],2)
parametros[,6] <- round(comp$VarComp[25:30],2)
parametros <- as.data.frame(parametros)
parametros$traits <- traits


parametros %>% gt() %>% tab_options(table.font.size = pct(75))

```


## para aqui


### script luciano
```{r}
library(magrittr)
     # log likelihood of the model, AIC, convergence T/F
     modelfit<-summary(modelconj)$logo
     # number of groups for factors, could be used to compute DF 
     groups<-summary(modelconj)$groups

     # variance components
     varcomp<-summary(modelconj)$varcomp
     
     # genotypic variance
     Vg<-modelconj$sigma$Acession_name %>% as.vector() %>% mean()

     # Mean error-variance across trials 
     ## across heterogeneous error variance estimates
     meanHetVarE<-modelconj$sigma$units %>% mean()
     
     # Mean number of reps per accession
     meanNreps<-dados3 %>% count(Acession_name) %$% mean(n)
     
     # Broad-sense heritability
     H2<-Vg/(Vg+(meanHetVarE/meanNreps))
     
 # Extract the BLUPs and PEVs, compute Reliability (REL), 
     # de-regressed BLUPs and weights for downstream analysis
     blups<-modelconj$U$Acession_name$Value %>% 
          tibble(Acession_name=names(.),BLUP=.) %>% 
          mutate(Acession_name=gsub("Acession_name","",Acession_name),
                 PEV=diag(modelconj$PevU$Acession_name$Value), # prediction error variance
                 REL=1-PEV/Vg, # Reliability
                 drgBLUP=BLUP/REL, # De-regressed BLUP
                 WT=(1-H2)/((0.1 + (1-REL)/REL)*H2) # weight for downstream
          )
     
     # Combine all outputs into one object the function can return() 
     out<-tibble(H2=H2,meanHetVarE=meanHetVarE,meanNreps=meanNreps,
              #  modelfit=list(modelfit),
                 groups=list(groups),
                 blups=list(blups),
                 varcomp=list(varcomp),
                 outliers=list(outliers))


```






