---
title: "PCA"
author: "massaine"
date: "2022-07-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(rstatix)
library(emmeans)
library(ggpubr)
library(gdata)
library(ggfortify)
library(stringr)
library(ggplot2)
library(RColorBrewer)
library(ggpubr)
library(gridExtra)
library(adegenet)
library(factoextra)
library(RColorBrewer)
library(dplyr)
library(viridis)
install.packages("")
load(file=here::here("output","blups_EP.RData"))
```

## EP 1
```{r}
rownames(blupsL[[1]]) <- gsub("Acession_name","",rownames(blupsL[[1]]))
colnames(blupsL[[1]]) <- c("ND1R","NER","A1R","NM","NP","NTF")

dadosPCA3 <- as.data.frame(scale(blupsL[[1]], center = TRUE, scale = TRUE))

pca_raw <- prcomp(dadosPCA3)
pcaplot <- autoplot(pca_raw, data = blupsL[[1]]) + theme_bw() + 
  ylim(-0.5, 0.5) + xlim(-0.5, 0.5) + 
  ggtitle("EP1 - PCA") +  theme(legend.title = element_blank()) 


### plots  (figura 3)
plotKMEANS1 <- fviz_nbclust(dadosPCA3, kmeans, method = "silhouette")
k2.1 <- kmeans(dadosPCA3, centers = 2, nstart = 25)
p3.1 <- fviz_cluster(k2.1,  data = dadosPCA3) + ggtitle("Epoca 1") + theme_bw()
dadosPCA3$cluster <- as.factor(k2.1$cluster)

# plots (figura 4)
pca1 <- autoplot(pca_raw, data = dadosPCA3, colour = 'cluster', 
                 label = TRUE, label.size = 3, loadings = TRUE, loadings.label = TRUE, 
                 loadings.label.size = 5,loadings.colour='gray') + ylim(-0.55, 0.5) + xlim(-0.5, 0.5) +  
                scale_colour_manual(values=c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF")) +  
                  theme_bw() + ggtitle("Epoca 1") 

ep1 <- as.data.frame(cbind(blupsL[[1]],as.factor(k2.1$cluster)))
colnames(ep1)[7] <- "cluster"
PCi_1<-data.frame(pca_raw$x,Cluster=dadosPCA3$cluster)
table(ep1$cluster)

```

## EP 2
```{r}
rownames(blupsL[[2]]) <- gsub("Acession_name","",rownames(blupsL[[2]]))
colnames(blupsL[[2]]) <-c("ND1R","NER","A1R","NM","NP","NTF")

dadosPCA3 <- as.data.frame(scale(blupsL[[2]], center = TRUE, scale = TRUE))

pca_raw <- prcomp(dadosPCA3)
pcaplot <- autoplot(pca_raw, data = blupsL[[2]]) + theme_bw() + 
  ylim(-0.5, 0.5) + xlim(-0.5, 0.5) + 
  ggtitle("EP2 - PCA") +  theme(legend.title = element_blank()) 

### plots  (figura 3)
plotKMEANS2 <- fviz_nbclust(dadosPCA3, kmeans, method = "silhouette")
k2.2 <- kmeans(dadosPCA3, centers = 2, nstart = 25)
p3.2 <- fviz_cluster(k2.2,  data = dadosPCA3) + ggtitle("Epoca 2") + theme_bw()
dadosPCA3$cluster <- as.factor(k2.2$cluster)

### plots  (figura 4)
pca2 <- autoplot(pca_raw, data = dadosPCA3, colour = 'cluster', 
                 label = TRUE, label.size = 3, loadings = TRUE, loadings.label = TRUE, 
                 loadings.label.size = 5,loadings.colour='gray') + ylim(-0.55, 0.5) + xlim(-0.5, 0.5) +  
                scale_colour_manual(values=c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF")) +  
                  theme_bw() + ggtitle("Epoca 2") 

ep2 <- as.data.frame(cbind(blupsL[[2]],as.factor(k2.2$cluster)))
colnames(ep2)[7] <- "cluster"
PCi_2<-data.frame(pca_raw$x,Cluster=dadosPCA3$cluster)
table(ep2$cluster)
```

## EP 3
```{r}
rownames(blupsL[[3]]) <- gsub("Acession_name","",rownames(blupsL[[3]]))
colnames(blupsL[[3]]) <-c("ND1R","NER","A1R","NM","NP","NTF")

dadosPCA3 <- as.data.frame(scale(blupsL[[3]], center = TRUE, scale = TRUE))
pca_raw <- prcomp(dadosPCA3)
pcaplot <- autoplot(pca_raw, data = blupsL[[3]]) + theme_bw() + 
  ylim(-0.5, 0.5) + xlim(-0.5, 0.5) + 
  ggtitle("ep3 - PCA") +  theme(legend.title = element_blank()) 

### plots  (figura 3)
plotKMEANS3 <- fviz_nbclust(dadosPCA3, kmeans, method = "silhouette")
k2.3 <- kmeans(dadosPCA3, centers = 5, nstart = 25)
p3.3 <- fviz_cluster(k2.3,  data = dadosPCA3) + ggtitle("Epoca 2") + theme_bw()
dadosPCA3$cluster <- as.factor(k2.3$cluster)

### plots  (figura 4)
pca3 <- autoplot(pca_raw, data = dadosPCA3, colour = 'cluster', 
                 label = TRUE, label.size = 3, loadings = TRUE, loadings.label = TRUE, 
                 loadings.label.size = 5,loadings.colour='gray') + ylim(-0.55, 0.5) + xlim(-0.5, 0.5) +  
                 scale_colour_manual(values=c("#7AD151FF","#2A788EFF","darkorchid3","orange","black")) +  
                 theme_bw() + ggtitle("Epoca 3") 

ep3 <- as.data.frame(cbind(blupsL[[3]],as.factor(k2.3$cluster)))
colnames(ep3)[7] <- "cluster"
PCi_3<-data.frame(pca_raw$x,Cluster=dadosPCA3$cluster)
table(ep3$cluster)
```


## EP4
```{r}
rownames(blupsL[[4]]) <- gsub("Acession_name","",rownames(blupsL[[4]]))
colnames(blupsL[[4]]) <-c("ND1R","NER","A1R","NM","NP","NTF")
dadosPCA3 <- as.data.frame(scale(blupsL[[4]], center = TRUE, scale = TRUE))

pca_raw <- prcomp(dadosPCA3)
pcaplot <- autoplot(pca_raw, data = blupsL[[4]]) + theme_bw() + 
  ylim(-0.5, 0.5) + xlim(-0.5, 0.5) + 
  ggtitle("ep4 - PCA") +  theme(legend.title = element_blank()) 


### plots  (figura 3)

plotKMEANS4 <- fviz_nbclust(dadosPCA3, kmeans, method = "silhouette")
k2.4 <- kmeans(dadosPCA3, centers = 4, nstart = 25)
p3.4 <- fviz_cluster(k2.4,  data = dadosPCA3) + ggtitle("Epoca 2") + theme_bw()
dadosPCA3$cluster <- as.factor(k2.4$cluster)


### plots  (figura 4)
pca4 <- autoplot(pca_raw, data = dadosPCA3, colour = 'cluster', 
                 label = TRUE, label.size = 3, loadings = TRUE, loadings.label = TRUE, 
                 loadings.label.size = 5,loadings.colour='gray') + ylim(-0.55, 0.5) + xlim(-0.5, 0.5) +  
                scale_colour_manual(values=c("#7AD151FF","#2A788EFF","#440154FF","orange","black")) +  
                  theme_bw() + ggtitle("Epoca 4") 

ep4 <- as.data.frame(cbind(blupsL[[4]],as.factor(k2.4$cluster)))
colnames(ep4)[7] <- "cluster"
PCi_4 <- data.frame(pca_raw$x,Cluster=dadosPCA3$cluster)
table(ep4$cluster)


```

## salvar plots
```{r}
tiff(file = "Figura_PCA_Epocas.tiff", width = 26, height = 26, res = 700, compression = "lzw", units = "cm")
grid.arrange(pca1,
             pca2,
             pca3,
             pca4,ncol=2)
dev.off()

tiff(file = "Figura_Kmeans.tiff", width = 30, height = 8, res = 700, compression = "lzw", units = "cm")
grid.arrange(plotKMEANS1,
             plotKMEANS2,
             plotKMEANS3,
             plotKMEANS4,
             ncol=4)
dev.off()
```

## PLOTS CLUSTERS EP1 (figura 5)
```{r}
########################### teste tukey

#####NP


ep1$cluster <- as.factor(ep1$cluster)

stat.test.1 <- ep1%>%
  #group_by() %>%
  tukey_hsd(NP ~cluster ) 
stat.test.1 

stat.test.1 <- stat.test.1 %>% add_xy_position(x = "cluster", scales = "free")



p1<- ggboxplot(ep1, x = "cluster", y = "NP", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.1, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NP")+ ylim(3,25)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))

############NM

stat.test.2 <- ep1%>%
  #group_by() %>%
  tukey_hsd(NM ~cluster ) 
stat.test.2 

stat.test.2 <- stat.test.2 %>% add_xy_position(x = "cluster", scales = "free")

p2<- ggboxplot(ep1, x = "cluster", y = "NM", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.2, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NM")+ ylim(0.2,1.3)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))

########### ND1R

stat.test.3 <- ep1%>%
  #group_by() %>%
  tukey_hsd( ND1R~cluster ) 
stat.test.3

stat.test.3 <- stat.test.3 %>% add_xy_position(x = "cluster", scales = "free")

p3<- ggboxplot(ep1, x = "cluster", y = "ND1R", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.3, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "ND1R")+ ylim(70,350)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))

########### NER

stat.test.4 <- ep1%>%
  #group_by() %>%
  tukey_hsd( NER~cluster ) 
stat.test.4

stat.test.4 <- stat.test.4 %>% add_xy_position(x = "cluster", scales = "free")

p4<- ggboxplot(ep1, x = "cluster", y = "NER", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.4, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NER")+ ylim(2.2,11)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))

########### NTF

stat.test.5 <- ep1%>%
  #group_by() %>%
  tukey_hsd( NTF~cluster ) 
stat.test.5

stat.test.5 <- stat.test.5 %>% add_xy_position(x = "cluster", scales = "free")

p5<- ggboxplot(ep1, x = "cluster", y = "NTF", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.5, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NTF")+ ylim(0,2)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))



########### A1R

stat.test.6 <- ep1%>%
  #group_by() %>%
  tukey_hsd( A1R~cluster ) 
stat.test.6

stat.test.6 <- stat.test.6 %>% add_xy_position(x = "cluster", scales = "free")

p6<- ggboxplot(ep1, x = "cluster", y = "A1R", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.6, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "A1R")+ ylim(30,350)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))

grid.arrange(p1,p2,p3,p4,p5,p6, ncol=6)

```

## PLOTS CLUSTERS EP2 (figura 5)
```{r}

#####NP

ep2$cluster <- as.factor(ep2$cluster)

stat.test.7 <- ep2%>%
  #group_by() %>%
  tukey_hsd(NP ~cluster ) 
stat.test.7 

stat.test.7 <- stat.test.7 %>% add_xy_position(x = "cluster", scales = "free")

g1<- ggboxplot(ep2, x = "cluster", y = "NP", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.7, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NP")+ ylim(3,25)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))

############NM

stat.test.8 <- ep2%>%
  #group_by() %>%
  tukey_hsd(NM ~cluster ) 
stat.test.8

stat.test.8 <- stat.test.8 %>% add_xy_position(x = "cluster", scales = "free")

g2<- ggboxplot(ep2, x = "cluster", y = "NM", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.8, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NM")+ ylim(0.2,1.3)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))

########### ND1R

stat.test.9 <- ep2%>%
  #group_by() %>%
  tukey_hsd( ND1R~cluster ) 
stat.test.9

stat.test.9 <- stat.test.9 %>% add_xy_position(x = "cluster", scales = "free")

g3<- ggboxplot(ep2, x = "cluster", y = "ND1R", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.3, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "ND1R")+ ylim(70,350)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))


########### NER

stat.test.10 <- ep2%>%
  #group_by() %>%
  tukey_hsd( NER~cluster ) 
stat.test.10

stat.test.10 <- stat.test.10 %>% add_xy_position(x = "cluster", scales = "free")

g4<- ggboxplot(ep2, x = "cluster", y = "NER", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.10, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NER")+ ylim(2.2,11)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))

########### NTF

stat.test.11 <- ep2%>%
  #group_by() %>%
  tukey_hsd( NTF~cluster ) 
stat.test.11

stat.test.11 <- stat.test.11 %>% add_xy_position(x = "cluster", scales = "free")

g5<- ggboxplot(ep2, x = "cluster", y = "NTF", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.11, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NTF")+ ylim(0,2)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))


########### A1R

stat.test.12 <- ep2%>%
  #group_by() %>%
  tukey_hsd( A1R~cluster ) 
stat.test.12

stat.test.12 <- stat.test.12 %>% add_xy_position(x = "cluster", scales = "free")

g6<- ggboxplot(ep2, x = "cluster", y = "A1R", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.12, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "A1R")+ ylim(30,350)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","#440154FF","#FDE725FF"))



grid.arrange(g1,g2,g3,g4,g5,g6, ncol=6)
```
 

## plots ep 3 (figura 5)

```{r}

#####NP

ep3$cluster <- as.factor(ep3$cluster)

stat.test.13 <- ep3%>%
  #group_by() %>%
  tukey_hsd(NP ~cluster ) 
stat.test.13 

stat.test.13 <- stat.test.13 %>% add_xy_position(x = "cluster", scales = "free")


h1<- ggboxplot(ep3, x = "cluster", y = "NP", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.13, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NP")+ ylim(3,25)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black"))

############NM

stat.test.14 <- ep3%>%
  #group_by() %>%
  tukey_hsd(NM ~cluster ) 
stat.test.14 

stat.test.14 <- stat.test.14 %>% add_xy_position(x = "cluster", scales = "free")

h2<- ggboxplot(ep3, x = "cluster", y = "NM", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.14, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NM")+ ylim(0.2,1.3)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black"))

########### ND1R

stat.test.15 <- ep3%>%
  #group_by() %>%
  tukey_hsd( ND1R~cluster ) 
stat.test.15

stat.test.15 <- stat.test.15 %>% add_xy_position(x = "cluster", scales = "free")

h3<- ggboxplot(ep3, x = "cluster", y = "ND1R", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.15, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "ND1R")+ ylim(70,350)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black"))

########### NER

stat.test.16 <- ep3%>%
  #group_by() %>%
  tukey_hsd( NER~cluster ) 
stat.test.16

stat.test.16 <- stat.test.16 %>% add_xy_position(x = "cluster", scales = "free")

h4<- ggboxplot(ep3, x = "cluster", y = "NER", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.16, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NER")+ ylim(2.2,11)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black"))

########### NTF

stat.test.17 <- ep3%>%
  #group_by() %>%
  tukey_hsd( NTF~cluster ) 
stat.test.17

stat.test.17 <- stat.test.17 %>% add_xy_position(x = "cluster", scales = "free")

h5<- ggboxplot(ep3, x = "cluster", y = "NTF", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.17, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NTF")+ ylim(0,2)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black")) 

########### A1R

stat.test.18 <- ep3%>%
  #group_by() %>%
  tukey_hsd( A1R~cluster ) 
stat.test.18

stat.test.18 <- stat.test.18 %>% add_xy_position(x = "cluster", scales = "free")

h6<- ggboxplot(ep3, x = "cluster", y = "A1R", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.18, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "A1R")+ ylim(30,350)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black")) 



grid.arrange(h1,h2,h3,h4,h5,h6, ncol=3)


```

## plots ep 4  (figura 5)
```{r}

#####NP

ep4$cluster <- as.factor(ep4$cluster)

stat.test.19 <- ep4%>%
  #group_by() %>%
  tukey_hsd(NP ~cluster ) 
stat.test.19 

stat.test.19 <- stat.test.19 %>% add_xy_position(x = "cluster", scales = "free")


d1<- ggboxplot(ep4, x = "cluster", y = "NP", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.19, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NP")+ ylim(3,25)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black"))

############NM

stat.test.20 <- ep4%>%
  #group_by() %>%
  tukey_hsd(NM ~cluster ) 
stat.test.20 

stat.test.20 <- stat.test.20 %>% add_xy_position(x = "cluster", scales = "free")

d2<- ggboxplot(ep4, x = "cluster", y = "NM", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.20, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NM")+ ylim(0.2,1.3)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black"))

########## ND1R

stat.test.21 <- ep4%>%
  #group_by() %>%
  tukey_hsd( ND1R~cluster ) 
stat.test.21

stat.test.21 <- stat.test.21 %>% add_xy_position(x = "cluster", scales = "free")

d3<- ggboxplot(ep4, x = "cluster", y = "ND1R", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.21, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "ND1R")+ ylim(70,280)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black"))

########### NER

stat.test.22 <- ep4%>%
  #group_by() %>%
  tukey_hsd( NER~cluster ) 
stat.test.22

stat.test.22 <- stat.test.22 %>% add_xy_position(x = "cluster", scales = "free")

d4<- ggboxplot(ep4, x = "cluster", y = "NER", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.22, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NER")+ ylim(2.2,11)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black"))


########### NTF

stat.test.23 <- ep4%>%
  #group_by() %>%
  tukey_hsd( NTF~cluster ) 
stat.test.23

stat.test.23 <- stat.test.23 %>% add_xy_position(x = "cluster", scales = "free")

d5<- ggboxplot(ep4, x = "cluster", y = "NTF", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.23, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NTF")+ ylim(0,2)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black"))

########### A1R

stat.test.24 <- ep4%>%
  #group_by() %>%
  tukey_hsd( A1R~cluster ) 
stat.test.24

stat.test.24 <- stat.test.24 %>% add_xy_position(x = "cluster", scales = "free")

d6<- ggboxplot(ep4, x = "cluster", y = "A1R", fill = "cluster",outlier.shape = NA)+ stat_pvalue_manual(stat.test.24, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "A1R")+ ylim(30,350)+
  theme(legend.position="none")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange","black"))
 

grid.arrange(d1,d2,d3,d4,d5,d6, ncol=6)
```

##  salvar final plot clustrs 
```{r}
tiff(file = "Figura_Cluster.tiff", width = 22, height = 30, res = 700, compression = "lzw", units = "cm")
grid.arrange(p1,g1,h1,d1,p2,g2,h2,d2,p5,g5,h5,d5,ncol=4)
dev.off()

tiff(file = "Figura_Cluster_Pt2.tiff", width = 22, height = 30, res = 700, compression = "lzw", units = "cm")
grid.arrange(p4,g4,h4,d4,p3,g3,h3,d3,p6,g6,h6,d6,ncol=4)            
dev.off()
```


