---
title: "Plots_descritivos"
author: "massaine"
date: "2022-07-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r}
library(gdata)
library(ggfortify)
library(stringr)
library(ggplot2)
library(RColorBrewer)
library(ggpubr)
library(gridExtra)
library(adegenet)
library(factoextra)
library(RColorBrewer)
library(dplyr)
library(viridis)
library(rstatix)
library(emmeans)
library(ggpubr)
load(file=here::here("output","blups_EP.RData"))
```

## BOXPLOTS descritivos
```{r}
ep1 <- as.data.frame(blupsL[[1]])
ep1$clone <- rownames(ep1)
ep1$Epoca <- 1
ep2 <- as.data.frame(blupsL[[2]])
ep2$clone <- rownames(ep2)
ep2$Epoca <- 2
ep3 <- as.data.frame(blupsL[[3]])
ep3$clone <- rownames(ep3)
ep3$Epoca <- 3
ep4 <- as.data.frame(blupsL[[4]])
ep4$clone <- rownames(ep4)
ep4$Epoca <- 4
BLUPs <- rbind(ep1,ep2,ep3,ep4)
colnames(BLUPs) <- c("ND1R","NER","A1R","NM","NP","NTF","clone","Epoca")
BLUPs$clone <- gsub("Acession_name","",BLUPs$clone)
BLUPs$clone <- as.factor(BLUPs$clone)
BLUPs$Epoca <- as.factor(BLUPs$Epoca)

```

## BOXPLOT GERAL (figura 2)
```{r}

BLUPs$Epoca <- as.factor(BLUPs$Epoca)

############NP

stat.test.a <- BLUPs%>%
  #group_by() %>%
  tukey_hsd(NP ~Epoca ) 
stat.test.a

stat.test.a <- stat.test.a %>% add_xy_position(x = "Epoca", scales = "free")

c1<- ggboxplot(BLUPs, x = "Epoca", y = "NP",outlier.shape = NA)+ stat_pvalue_manual(stat.test.a, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NP")+ ylim(2,20)+theme(legend.position="none")+geom_boxplot(outlier.shape = NA,fill="#7AD151FF")+xlab("Epocas de plantio") 

############NM 

stat.test.b <- BLUPs%>%
  #group_by() %>%
  tukey_hsd(NM ~Epoca ) 
stat.test.b

stat.test.b <- stat.test.b %>% add_xy_position(x = "Epoca", scales = "free")

c2<- ggboxplot(BLUPs, x = "Epoca", y = "NM",outlier.shape = NA)+ stat_pvalue_manual(stat.test.b, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NM")+ ylim(0.2,1)+theme(legend.position="none")+geom_boxplot(outlier.shape = NA,fill="#7AD151FF")+  xlab("Epocas de plantio") 

############ND1R

stat.test.c <- BLUPs%>%
  #group_by() %>%
  tukey_hsd(ND1R ~Epoca ) 
stat.test.c

stat.test.c <- stat.test.c %>% add_xy_position(x = "Epoca", scales = "free")


c3<- ggboxplot(BLUPs, x = "Epoca", y = "ND1R",outlier.shape = NA)+ stat_pvalue_manual(stat.test.c, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "ND1R")+ ylim(50,380)+theme(legend.position="none")+geom_boxplot(outlier.shape = NA,fill="#7AD151FF")+  xlab("Epocas de plantio") 

############NER


stat.test.d <- BLUPs%>%
  #group_by() %>%
  tukey_hsd(NER ~Epoca ) 
stat.test.d

stat.test.d <- stat.test.d %>% add_xy_position(x = "Epoca", scales = "free")


c4<- ggboxplot(BLUPs, x = "Epoca", y = "NER",outlier.shape = NA)+ stat_pvalue_manual(stat.test.d, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NER")+ ylim(2,10)+theme(legend.position="none")+geom_boxplot(outlier.shape = NA,fill="#7AD151FF")+  xlab("Epocas de plantio") 

############NTF
stat.test.e <- BLUPs%>%
  #group_by() %>%
  tukey_hsd(NTF ~Epoca ) 
stat.test.e

stat.test.e <- stat.test.e %>% add_xy_position(x = "Epoca", scales = "free")


c5<- ggboxplot(BLUPs, x = "Epoca", y = "NTF",outlier.shape = NA)+ stat_pvalue_manual(stat.test.e, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "NTF")+ ylim(0,1.5)+theme(legend.position="none")+geom_boxplot(outlier.shape = NA,fill="#7AD151FF")+  xlab("Epocas de plantio") 


############A1R
stat.test.f <- BLUPs%>%
  #group_by() %>%
  tukey_hsd(A1R~Epoca ) 
stat.test.f

stat.test.f <- stat.test.f %>% add_xy_position(x = "Epoca", scales = "free")


c6<- ggboxplot(BLUPs, x = "Epoca", y = "A1R",outlier.shape = NA)+ stat_pvalue_manual(stat.test.f, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_bw()+ labs(y = "A1R")+ ylim(25,300)+theme(legend.position="none")+geom_boxplot(outlier.shape = NA,fill="#7AD151FF")+  xlab("Epocas de plantio") 


```

## salvar  (figura 2)
```{r}
tiff(file = "Figura_boxplot_Epocas_geral.tiff", width = 14, height = 14, res = 700, compression = "lzw", units = "cm")
grid.arrange(c3,c1,c2,c5,c4,c6,ncol=3)
dev.off()
```

## BOX PLOT POR GENOTIPOS ( figuras s1 a s6)  
```{r}
######################NP

dados3$Epoca <- as.factor(dados3$Epoca)
stat.test.g <- dados3%>%
  group_by(Acession_name) %>%
  tukey_hsd(NP~Epoca ) 
stat.test.g

stat.test.g <- stat.test.g %>% add_xy_position(x = "Epoca", scales = "free")

NP<- ggboxplot(dados3, x = "Epoca", y = "NP",fill="Epoca",outlier.shape = NA)+ stat_pvalue_manual(stat.test.g, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_classic()+theme(legend.position="none")+ylim(2,32)+
  ylab("Nota de florescimento ponderado")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange"))+facet_wrap(~Acession_name, ncol = 6)

tiff(file = "NP_boxplot_Epocas_clone.tiff", width = 22, height = 26, res = 700, compression = "lzw", units = "cm")
NP
dev.off()
```

```{r}
######################NM

dados3$Epoca <- as.factor(dados3$Epoca)
stat.test.h <- dados3%>%
  group_by(Acession_name) %>%
  tukey_hsd(NM~Epoca ) 
stat.test.h

stat.test.h <- stat.test.h %>% add_xy_position(x = "Epoca", scales = "free")

NM<- ggboxplot(dados3, x = "Epoca", y = "NM",fill="Epoca",outlier.shape = NA)+ stat_pvalue_manual(stat.test.h, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_classic()+theme(legend.position="none")+ylim(0,1.6)+
  ylab("Nota média de florescimento")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange"))+facet_wrap(~Acession_name, ncol = 6)


tiff(file = "NM_boxplot_Epocas_clone.tiff", width = 22, height = 26, res = 700, compression = "lzw", units = "cm")
NM
dev.off()
```

```{r}
######################NTF

stat.test.i <- dados3%>%
  group_by(Acession_name) %>%
  tukey_hsd(NumTFruto~Epoca ) 
stat.test.i

stat.test.i <- stat.test.i %>% add_xy_position(x = "Epoca", scales = "free")

NTF<- ggboxplot(dados3, x = "Epoca", y = "NumTFruto",fill="Epoca",outlier.shape = NA)+ stat_pvalue_manual(stat.test.i, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_classic()+theme(legend.position="none")+ylim(0,6)+
  ylab("Numero total de frutos")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange"))+facet_wrap(~Acession_name, ncol = 6)


tiff(file = "NTF_boxplot_Epocas_clone.tiff", width = 22, height = 26, res = 700, compression = "lzw", units = "cm")
NTF
dev.off()
```


```{r}
######################NER

stat.test.j <- dados3%>%
  group_by(Acession_name) %>%
  tukey_hsd(NumEvRam~Epoca ) 
stat.test.j

stat.test.j <- stat.test.j %>% add_xy_position(x = "Epoca", scales = "free")

NER<- ggboxplot(dados3, x = "Epoca", y = "NumEvRam",fill="Epoca",outlier.shape = NA)+ stat_pvalue_manual(stat.test.j, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_classic()+theme(legend.position="none")+ylim(0,15)+
  ylab("Numero de eventos de ramificação")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange"))+facet_wrap(~Acession_name, ncol = 6)


tiff(file = "NER_boxplot_Epocas_clone.tiff", width = 22, height = 26, res = 700, compression = "lzw", units = "cm")
NER
dev.off()
```


```{r}
######################ND1R

stat.test.k <- dados3%>%
  group_by(Acession_name) %>%
  tukey_hsd(DAPR1ano_Ext~Epoca ) 
stat.test.k

stat.test.k <- stat.test.k %>% add_xy_position(x = "Epoca", scales = "free")


D1R<- ggboxplot(dados3, x = "Epoca", y = "DAPR1ano_Ext",fill="Epoca",outlier.shape = NA)+ stat_pvalue_manual(stat.test.k, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_classic()+theme(legend.position="none")+ylim(50,505)+
  ylab("Dias início de ramificação")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange"))+facet_wrap(~Acession_name, ncol = 6)


tiff(file = "DI1R_boxplot_Epocas_clone.tiff", width = 22, height = , res = 700, compression = "lzw", units = "cm")
D1R
dev.off()
```


```{r}

######################A1R

stat.test.l <- dados3%>%
  group_by(Acession_name) %>%
  tukey_hsd(CompR~Epoca ) 
stat.test.l

stat.test.l <- stat.test.l %>% add_xy_position(x = "Epoca", scales = "free")

A1R<- ggboxplot(dados3, x = "Epoca", y = "CompR",fill="Epoca",outlier.shape = NA)+ stat_pvalue_manual(stat.test.l, hide.ns = TRUE, tip.length = 0, step.increase = 0)+ theme_classic()+theme(legend.position="none")+ylim(0,420)+
  ylab("Altura da primeira ramificação")+scale_fill_manual(values = c("#7AD151FF","#2A788EFF","darkorchid3","orange"))+facet_wrap(~Acession_name, ncol = 6)


tiff(file = "A1R_boxplot_Epocas_clone.tiff", width = 22, height = 28, res = 700, compression = "lzw", units = "cm")
A1R
dev.off()

```

